source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:nytm/ios-podspecs.git'

platform :ios, '9.0'

use_frameworks!

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths
    platform :ios, '9.0'

    ${INCLUDED_PODS}
  end
end
